export const all = [
  {
    popularity: 88.388,
    vote_count: 198,
    video: false,
    poster_path: '/jjMJy5OxJHpFIaboCklDIYdcfpD.jpg',
    id: 504562,
    adult: false,
    backdrop_path: '/mJoZVYRTtPI6aMPb1UanuXFC1Zw.jpg',
    original_language: 'en',
    original_title: 'Motherless Brooklyn',
    genre_ids: [18, 9648, 53],
    title: 'Motherless Brooklyn',
    vote_average: 7.1,
    overview:
      "Lionel Essrog, a private detective living with Tourette syndrome, ventures to solve the murder of his mentor and best friend — a mystery that carries him from the gin-soaked jazz clubs of Harlem to the slums of Brooklyn to the gilded halls of New York's power brokers.",
    release_date: '2019-10-31',
  },
  {
    popularity: 93.51,
    vote_count: 552,
    video: false,
    poster_path: '/mSmiB8XjUnR1GSIljuCPGsk0cwX.jpg',
    id: 331482,
    adult: false,
    backdrop_path: '/3uTxPIdVEXxHpsHOHdJC24QebBV.jpg',
    original_language: 'en',
    original_title: 'Little Women',
    genre_ids: [18, 10749],
    title: 'Little Women',
    vote_average: 8.1,
    overview:
      'Four sisters come of age in America in the aftermath of the Civil War.',
    release_date: '2019-12-25',
  },
];
